#!/bin/bash
CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_3_580304/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_3_580304/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_3_580304/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_4_564216/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_4_564216/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s03_4_564216/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_3_320000/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_3_320000/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_3_320000/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_4_159824/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_4_159824/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s05_4_159824/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_3_563696/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_3_563696/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_3_563696/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_4_368756/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_4_368756/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s10_4_368756/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_3_249552/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_3_249552/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_3_249552/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_4_257112/0             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_4_257112/1             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=1             python hyper_pixelNN.py             --network yu             --dataset KSC             --eval_period 200             --num_epochs 100000             --mask_root /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/yu/KSC_strictsinglesite_trainval_s20_4_257112/2             --network_spatial_size 5             --terminate_if_n_nondecreasing_evals 10;
