#!/bin/bash
CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_3_580304/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_3_580304/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_3_580304.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_3_580304/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_4_564216/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_4_564216/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s03_4_564216.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s03_4_564216/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_3_320000/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_3_320000/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_3_320000.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_3_320000/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_4_159824/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_4_159824/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s05_4_159824.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s05_4_159824/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_3_563696/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_3_563696/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_3_563696.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_3_563696/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_4_368756/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_4_368756/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s10_4_368756.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s10_4_368756/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_3_249552/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_3_249552/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_3_249552.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_3_249552/2             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_4_257112/0             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_4_257112/1             --terminate_if_n_nondecreasing_evals 10;

CUDA_VISIBLE_DEVICES=0             python hyper_pixelNN.py             --dataset KSC             --npca_components 5             --batch_size 100             --lr 0.00005             --network DFFN_3tower_2depth             --network_spatial_size 25             --eval_period 20             --num_epochs 100000             --mask_root  /scratch0/ilya/locDoc/data/hyperspec/KSC_strictsinglesite_trainval_s20_4_257112.mat             --model_root /scratch0/ilya/locDoc/pyfst/models/dffn/KSC_strictsinglesite_trainval_s20_4_257112/2             --terminate_if_n_nondecreasing_evals 10;
